apiVersion: v1
kind: ConfigMap
metadata:
  name: access-manager
  namespace: access-manager
  labels:
    app.kubernetes.io/name: access-manager
    app.kubernetes.io/component: config
data:
  DATABASE_DRIVER: "postgres"
  HTTP_ADDR: "0.0.0.0:8080"
  MIGRATIONS_DIR: "migrations/postgres"
  CORS_ALLOWED_ORIGINS: "none"
  SHUTDOWN_TIMEOUT_SECONDS: "60"
