apiVersion: v1
kind: Service
metadata:
  name: access-manager
  namespace: access-manager
  labels:
    app.kubernetes.io/name: access-manager
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: access-manager
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
