apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "access-manager.fullname" . }}
  namespace: access-manager
  labels:
    {{- include "access-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  DATABASE_DRIVER: {{ .Values.config.databaseDriver | quote }}
  HTTP_ADDR: {{ .Values.config.httpAddr | quote }}
  MIGRATIONS_DIR: {{ .Values.config.migrationsDir | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.corsAllowedOrigins | quote }}
  SHUTDOWN_TIMEOUT_SECONDS: {{ .Values.config.shutdownTimeoutSeconds | quote }}
