{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: access-manager
  labels:
    {{- include "access-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    {{- include "access-manager.postgresSelectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
{{- end }}
